### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Alexis01** [h2non/nightmare-google-oauth2#5]
Hi, 

I've got this error: 
                    [Error: Cannot retrieve the token. Timeout exceeded]

After that, the next error repeats every time:
phantom stdout: TypeError: 'null' is not an object (evaluating 'element.dispatchEvent')
phantom stdout:   phantomjs://webpage.evaluate():5
  phantomjs://webpage.evaluate():6
  phantomjs://webpage.evaluate():6

Node v5.2.0

**Comment by h2non** [comment]
Google usually changes the login UI every couple of months. Since the implementation is coupled to DOM layer, there's required to update the code as well every time Google does some change. 

I don't have time to invest on this now, but feel free to go ahead. I'll accept PR.

**Comment by h2non** [comment]
This was fixed in `0.1.6` and `0.2.0`.
